language: csharp
solution: ZoraSharp.sln
sudo: false
install:
  - nuget restore ZoraSharp.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ZoraSharp.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./test/bin/Release/ZoraSharp.Tests.dll
