version: 2.1.{build}
configuration: Debug
before_build:
- nuget restore ZoraSharp.sln
build:
  project: ZoraSharp.sln
  verbosity: minimal
artifacts:
- path: src\bin\$(configuration)\*.dll
after_test:
- nuget.exe install OpenCover -ExcludeVersion
- OpenCover\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:"test\bin\%CONFIGURATION%\ZoraSharp.Tests.dll --result=myresults.xml;format=AppVeyor" -returntargetcode -filter:"+[*]* -[ZoraSharp.Tests]*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -hideskipped:All -output:coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"
